server:
  dev:
    enabled: true
  extraArgs: '-dev-root-token-id=root -dev-plugin-dir=/usr/local/libexec/vault'
  volumes:
    - name: plugins
      emptyDir: {}
  volumeMounts:
    - mountPath: /usr/local/libexec/vault
      name: plugins
      readOnly: false
  extraInitContainers:
    - name: kubesecrets-plugin
      image: ghcr.io/the-mesh-for-data/vault-plugin-secrets-kubernetes-reader:latest
      imagePullPolicy: Always
      command: [/bin/sh, -ec]
      args:
        - cp /vault-plugin-secrets-kubernetes-reader /usr/local/libexec/vault/vault-plugin-secrets-kubernetes-reader &&
          cp /startup_plugin.sh /usr/local/libexec/vault/startup_plugin.sh
      volumeMounts:
      - name: plugins
        mountPath: /usr/local/libexec/vault
        readOnly: false
  extraEnvironmentVars:
    VAULT_API_ADDR: http://127.0.0.1:8200
    VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    VAULT_ADDR: http://127.0.0.1:8200
  # Used to define commands to run after the pod is ready.
  # This can be used to automate processes such as initialization
  # or boostrapping auth methods.
  postStart:
    - /bin/sh
    - -c
    - /usr/local/libexec/vault/startup_plugin.sh
