definitions:
  Interface:
    oneOf:
      - properties:
          protocol:
            enum: [fybrik-arrow-flight]
          dataformat:
            enum: [arrow]
        required: [protocol, dataformat]
      - properties:
          protocol:
            enum: [kafka]
          dataformat:
            enum: [json, avro]
        required: [protocol, dataformat]
      - properties:
          protocol:
            enum: [s3]
          dataformat:
            enum: [csv, parquet]
        required: [protocol, dataformat]
      - properties:
          protocol:
            enum: [db2-jdbc]
          dataformat:
            enum: [db2-jdbc]
        required: [protocol, dataformat]