openapi: 3.0.1
info:
  license:
    name: Apache 2.0
  title: Policy Manager Service
  version: 1.0.0
servers:
- url: https://localhost:8080
paths:
  /getPoliciesDecisions:
    get:
      description: Rest API for returning policy decisions
      operationId: getPoliciesDecisions
      parameters:
      - content:
          application/json:
            schema:
              $ref: '#/components/schemas/policy_manager_request'
        description: Policy Manager Request Object
        explode: true
        in: query
        name: input
        required: true
        style: form
      - description: credentials to wkc connector
        explode: true
        in: query
        name: creds
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/policy_manager_response'
          description: successful operation
        "400":
          description: Invalid status value
      summary: getPoliciesDecisions
components:
  schemas:
    policy_manager_request:
      additionalProperties: false
      properties:
        context:
          $ref: '#/components/schemas/PolicyManagerRequestContext'
        action:
          $ref: '#/components/schemas/PolicyManagerRequestAction'
        resource:
          $ref: '#/components/schemas/Resource'
      required:
      - action
      - resource
      title: Policy Manager Request
      type: object
    PolicyManagerRequestAction:
      properties:
        actionType:
          $ref: '#/components/schemas/ActionType'
        processingLocation:
          $ref: '#/components/schemas/ProcessingLocation'
      type: object
    ActionType:
      enum:
      - read
      - write
      - delete
      type: string
    Resource:
      properties:
        name:
          description: Name of the data set
          type: string
        tags:
          $ref: '#/components/schemas/Tags'
        columns:
          items:
            $ref: '#/components/schemas/Resource_columns'
          type: array
      required:
      - name
      type: object
    policy_manager_response:
      additionalProperties: false
      example:
        result:
        - action:
            name: name
          policy: policy
        - action:
            name: name
          policy: policy
        decision_id: decision_id
      properties:
        decision_id:
          type: string
        result:
          items:
            $ref: '#/components/schemas/ResultItem'
          type: array
      required:
      - result
      title: Policy Manager Response
      type: object
    ResultItem:
      example:
        action:
          name: name
        policy: policy
      properties:
        policy:
          description: The policy on which the decision was based.
          type: string
        action:
          $ref: '#/components/schemas/Action'
      required:
      - action
      - policy
      type: object
    PolicyManagerRequestContext:
      additionalProperties: true
      type: object
    ProcessingLocation:
      type: string
    Tags:
      additionalProperties: true
      type: object
    Action:
      additionalProperties: true
      example:
        name: name
      properties:
        name:
          type: string
      required:
      - name
      type: object
    Resource_columns:
      properties:
        name:
          type: string
        tags:
          $ref: '#/components/schemas/Tags'
      required:
      - name
      type: object
