apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/instance: m4d
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: m4d
    app.kubernetes.io/version: latest
    control-plane: controller-manager
    helm.sh/chart: m4d-0.0.0
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: manager
      app.kubernetes.io/instance: m4d
      app.kubernetes.io/name: m4d
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/component: manager
        app.kubernetes.io/instance: m4d
        app.kubernetes.io/name: m4d
        control-plane: controller-manager
        m4d.ibm.com/componentType: manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --enable-application-controller
        - --enable-plotter-controller
        - --enable-blueprint-controller
        - --enable-motion-controller
        env:
        - name: ENABLE_WEBHOOKS
          value: 'true'
        - name: MOVER_IMAGE
          value: ghcr.io/the-mesh-for-data/mover:latest
        - name: IMAGE_PULL_POLICY
          value: null
        envFrom:
        - configMapRef:
            name: m4d-config
        - secretRef:
            name: vault-credentials
        image: ghcr.io/the-mesh-for-data/manager:latest
        imagePullPolicy: null
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources: {}
        securityContext: {}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext: {}
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
