# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

language: go

services:
- docker

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - asciidoctor
      - conntrack
      - ethtool

os:
- linux

go:
- "1.13"

git:
  depth: 3

cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.m2
  - $HOME/gopath/src/github.com/ibm/the-mesh-for-data/hack/tools/bin

go_import_path: github.com/ibm/the-mesh-for-data

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
-

jobs:
  include: 
  - stage: Build
    name: "Verify code and run unit tests"
    install:
    - make install-tools
    script:
    - make verify
    - make test

  - stage: Build
    name: "Build, integration-tests and push"
    install:
    - make install-tools
    env:
    - DOCKER_HOSTNAME=localhost:5000
    - DOCKER_NAMESPACE=m4d
    script:
    - make docker # Builds and pushes docker images locally
    - make kind || travis_terminate 1; # Setup local kind cluster
    - make cluster-prepare || travis_terminate 1; # Install 3rd party cluster dependencies
    - make deploy # Deploy components on cluster
    - make e2e # Run e2e test
    - make helm # Run helm and helm tests

    deploy:
      skip_cleanup: true
      provider: script
      script: echo "Nothing for now" # TODO tag all images to final names and push them
      on:
        branch: master

  # FIXME(hunchback): disabled as its' taking 15m to run
  # - stage: verify-license
  #   install:
  #   script:
  #   - make license

  - stage: Publish
    name: "Build and publish website"
    env:
    - WEBSITE_LOCAL_DIR=public
    script:
    - make -C website
    deploy:
      skip_cleanup: true
      provider: pages
      local_dir: website/$WEBSITE_LOCAL_DIR
      github_token: $GITHUB_TOKEN # Set in travis-ci dashboard
      on:
        branch: master

notifications:
  email: false
