definitions:
  PolicyManagerRequestContext:
    type: object
    additionalProperties: true
  Tags:
    type: object
    additionalProperties: true
  Action:
    type: object
    properties:
      name:
        type: string
    additionalProperties: true
    required:
      - name
  DatasetID:
    type: string
  ProcessingLocation:
    type: string
  AppInfo:
    type: object
  Protocol:
    type: string
  Dataformat:
    type: string
  Interface:
    type: object
    properties:
      protocol:
        $ref: "#/definitions/Protocol"
      dataformat:
        $ref: "#/definitions/Dataformat"
    additionalProperties: false
  Source:
    type: object
    properties:
      source:
        $ref: "#/definitions/Interface"
  Sink:
    type: object
    properties:
      sink:
        $ref: "#/definitions/Interface"
  Capability:
    properties:
      capability:
        enum: [copy, write, read, transform]
      supportedInterfaces:
        type: array
        items:
          type: object
          oneOf:
            - $ref: "#/definitions/Source"
            - $ref: "#/definitions/Sink"
      api:
        type: object
        properties:
          interfaceDetails:
            $ref: "#/definitions/Interface"
      actions:
        type: array
        items:
          type: object
          properties:
            id: 
              $ref: "#/definitions/Action"
