definitions:
  PolicyManagerRequestContext:
    type: object
    additionalProperties: true
  Tags:
    type: object
    additionalProperties: true
  Action:
    type: object
    properties:
      name:
        type: string
    additionalProperties: true
    required:
      - name
  DatasetID:
    type: string
  ProcessingLocation:
    type: string
  AppInfo:
    type: object
  Protocol:
    type: string
  Dataformat:
    type: string
  Interface:
    type: object
    properties:
      protocol:
        $ref: "#/definitions/Protocol"
      dataformat:
        $ref: "#/definitions/Dataformat"
    additionalProperties: false
