apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-metadata
data:
  ClusterName: {{ .Values.clusterMetadata.clusterName }}
  Region: {{ .Values.clusterMetadata.region }}
  Zone: {{ .Values.clusterMetadata.zone }}
  VaultAuthPath: {{ .Values.clusterMetadata.vaultAuthPath }}
