{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled .Values.coordinator.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "m4d.fullname" . }}-system-role
rules:
- apiGroups:
  - ""
  resources:
  - m4dstorageaccounts
  - m4dmodules
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
