{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: m4d-policymanager-config
data:
  {{- $files := .Files }}
  {{- range tuple "policymanager_request.structs.schema.json" "policymanager_response.structs.schema.json" "policymanager.structs.schema.json" "policymanager.values.schema.json" }}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}
{{- end }}