{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: m4d-app-config
data:
  {{- $files := .Files }}
  {{- range tuple "application-optional.values.json" "application.values.schema.json" }}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}
{{- end }}