{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled .Values.coordinator.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "m4d.fullname" . }}-system-role
rules:
- apiGroups:
  - ""
  resources:
  - plotters
  - m4dstorageaccounts
  - m4dmodules
  - datasets
  - secrets
  - secrets/finalizers
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - plotters/status
  verbs:
  - get
  - patch
  - update
{{- end }}
