{{- if .Values.manager.enabled }}
{{- if .Values.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "m4d.fullname" . }}-system-role
rules:
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - plotters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - plotters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - m4dstorageaccounts
  - m4dmodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - com.ie.ibm.hpsys
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - plotters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.m4d.ibm.com
  resources:
  - plotters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  - leases/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
{{- end }}

