{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: m4d-blueprints
  name: {{ template "m4d.fullname" . }}-blueprints-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
{{- end }}
