{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (and .Values.coordinator.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: m4d-system
  name: {{ template "m4d.fullname" . }}-system-role
rules:
- apiGroups:
  - ""
  resources:
  - plotters
  - m4dstorageaccounts
  - m4dmodules
  - datasets
  - secrets
  - secrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
