{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: m4d-catalog-config
data:
  {{- (.Files.Glob "files/taxonomy/catalog/**.json").AsConfig | nindent 2 }}
{{- end }}