{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (and .Values.worker.enabled)) }}
{{- if .Values.clusterScoped }}
# ClusterRole m4dapplication-editor allows managing m4dapplications
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: m4dapplication-editor
rules:
- apiGroups: ["app.m4d.ibm.com"]
  resources: ["m4dapplications"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["app.m4d.ibm.com"]
  resources: ["m4dapplications/status"]
  verbs: ["get", "update", "patch"]
{{- end }}
{{- end }}