# This file includes resources that are not yet mitigated properly to Helm
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: m4d-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: m4d-webhook-service
      namespace: m4d-system
      path: /mutate-motion-m4d-ibm-com-v1alpha1-batchtransfer
  failurePolicy: Fail
  name: mbatchtransfer.kb.io
  rules:
  - apiGroups:
    - motion.m4d.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - batchtransfers
- clientConfig:
    caBundle: Cg==
    service:
      name: m4d-webhook-service
      namespace: m4d-system
      path: /mutate-motion-m4d-ibm-com-v1alpha1-streamtransfer
  failurePolicy: Fail
  name: mstreamtransfer.kb.io
  rules:
  - apiGroups:
    - motion.m4d.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streamtransfers
---
apiVersion: v1
kind: Service
metadata:
  name: m4d-webhook-service
  namespace: m4d-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: m4d-serving-cert
  namespace: m4d-system
spec:
  dnsNames:
  - m4d-webhook-service.m4d-system.svc
  - m4d-webhook-service.m4d-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: m4d-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: m4d-selfsigned-issuer
  namespace: m4d-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: m4d-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: m4d-webhook-service
      namespace: m4d-system
      path: /validate-motion-m4d-ibm-com-v1alpha1-batchtransfer
  failurePolicy: Fail
  name: vbatchtransfer.kb.io
  rules:
  - apiGroups:
    - motion.m4d.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - batchtransfers
- clientConfig:
    caBundle: Cg==
    service:
      name: m4d-webhook-service
      namespace: m4d-system
      path: /validate-motion-m4d-ibm-com-v1alpha1-streamtransfer
  failurePolicy: Fail
  name: vstreamtransfer.kb.io
  rules:
  - apiGroups:
    - motion.m4d.ibm.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streamtransfers
