{{- if .Values.secureControlPlane }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar-default
  namespace: system
spec:
  egress:
  - hosts:
    - "*/*"
  outboundTrafficPolicy:
    mode: ALLOW_ANY

---
apiVersion: "security.istio.io/v1beta1"
# This policy enables mutual TLS traffic between every two workloads that have sidecar.
kind: "PeerAuthentication"
metadata:
  name: "premissive-mtls-in-control-plane"
  namespace: system
spec:
  mtls:
    # PERMISSIVE: Workloads accept both mutual TLS and plain text traffic
    mode: PERMISSIVE
{{- end }}