# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fybrik-crd-remote
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: 'remote'
    namespace: fybrik-system
  source:
    path: charts/fybrik-crd
    repoURL: 'https://github.com/fybrik/charts'
    targetRevision: HEAD
  sources: []
  project: default
