apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: m4d
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: m4d
    app.kubernetes.io/version: latest
    helm.sh/chart: m4d-0.0.0
  name: m4d-leader-election-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: m4d-leader-election-role
subjects:
- kind: ServiceAccount
  name: manager
  namespace: m4d-system
