strict: false

site_name: Fybrik
site_description: A cloud-native platform to control data usage
copyright: Made with ❤️ by Fybrik contributors.
repo_name: fybrik/fybrik
repo_url: https://github.com/fybrik/fybrik
edit_uri: edit/master/site/docs/

nav:
- About: index.md
- Get Started:
  - get-started/quickstart.md
  - Notebook samples:
    - Before we begin: samples/pre-steps.md
    - samples/notebook-read.md
    - samples/notebook-write.md
    - samples/delete-sample.md
    - samples/chaining-sample.md
    - samples/cleanup.md
- Concepts:
  - concepts/introduction.md
  - concepts/architecture.md
  - concepts/taxonomy.md
  - Plugins:
    - concepts/connectors.md
    - concepts/modules.md
    - concepts/vault_plugins.md
  - concepts/config-policies.md
  - concepts/optimizer.md
- Tasks:
  - tasks/control-plane-security.md
  - tasks/using-opa.md
  - tasks/multicluster.md
  - tasks/custom-taxonomy.md
  - tasks/performance.md
  - tasks/high-availability.md
  - tasks/infrastructure.md
  - tasks/data-plane-optimization.md
  - tasks/omd-discover-s3-asset.md
- Reference:
  - reference/crds.md
  - Connectors API:
    - Data catalog: reference/connectors-datacatalog/README.md
    - Policy manager: reference/connectors-policymanager/README.md
  - Components:
    - reference/ddc.md
    - reference/katalog.md
- Contribute:
  - About: contribute/index.md
  - contribute/environment.md
  - contribute/build-test.md
  - contribute/flow.md
  - contribute/logging.md
  - Documentation:
    - contribute/documentation/index.md
    - contribute/documentation/formatting.md
    - contribute/documentation/style.md
  - Plugins:
    - contribute/modules.md
    - Using OpenAPI Generator: contribute/openapi.md
- Publications: publications.md


extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fybrik/fybrik
  varRelease: "--version 0.7.0"

theme:
  name: material
  language: en
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  palette:
    primary: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  favicon: static/logo.png # this icon appears in the browser's tab
  logo: static/logo.png # this icon appears in the top left corner on each page

markdown_extensions:
  - toc:
      permalink: false
  - footnotes
  - admonition
  - meta
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  # disable temporarily because it's freezing the page
  - search:
      prebuild_index: python
      lang:
      - en
  - macros:
      include_yaml:
        - ./external.yaml
        - arrowFlight: "./arrowFlightReleases.yaml"
