# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Default values for m4d-cos2cos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# metadata associated with k8s resources
metadata:
  name: "cos2cos"
  namespace: "default"
  labels: []

# copies from source
source:
  connection:
    s3:
      endpoint: ""
      bucket: ""
      object_key: ""
  format: ""
  credentialLocation: ""

# copies to destination
destination:
  connection:
    s3:
      endpoint: ""
      bucket: ""
      object_key: ""
  format: ""
  credentialLocation: ""

transformations: []