kind: Deployment
apiVersion: apps/v1
metadata:
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: datauserclient
        image: image-registry.openshift-image-registry.svc:5000/cp4d/datauserclient:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: datauserserver
        image: image-registry.openshift-image-registry.svc:5000/cp4d/datauserserver:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: m4d-config
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: gui-vault-secret
              key: vault-root  
        - name: GEOGRAPHY
          value: US          
        ports:
        - containerPort: 8080
      restartPolicy: Always
