definitions:
  Capability:
    properties:
      capability:
        enum: [copy, write, read, transform]
      scope:
        enum: [asset, workload, cluster]
      supportedInterfaces:
        type: array
        items:
          type: object
          oneOf:
            - $ref: "#/definitions/Source"
            - $ref: "#/definitions/Sink"
      api:
        type: object
        properties:
          endpoint:
            type: object
            properties:
              port:
                type: integer
              scheme:
                enum: ['grpc']
          interfaceDetails:
            $ref: "#/definitions/Interface"
      actions:
        type: array
        items:
          $ref: "#/definitions/Action"
  Source:
    type: object
    properties:
      source:
        $ref: "#/definitions/Interface"
  Sink:
    type: object
    properties:
      sink:
        $ref: "#/definitions/Interface"