definitions:
  Capability:
    properties:
      capability:
        enum: [copy, write, read, transform]
      supportedInterfaces:
        type: array
        items:
          type: object
          oneOf:
            - $ref: "#/definitions/Source"
            - $ref: "#/definitions/Sink"
      api:
        type: object
        properties:
          interfaceDetails:
            $ref: "#/definitions/Interface"
      actions:
        type: array
        items:
          type: object
          properties:
            id: 
              $ref: "#/definitions/Action"
  Source:
    type: object
    properties:
      source:
        $ref: "#/definitions/Interface"
  Sink:
    type: object
    properties:
      sink:
        $ref: "#/definitions/Interface"