definitions:
  FybrikModule:
    properties:
      Type:
        enum: [service, config]
      Dependencies:
        DependencyType:
          enum: [module, connector, feature]
      Capabilities:
        - $ref: "#/definitions/Capabilities"
      