definitions:
  FybrikModule:
    properties:
      Type:
        enum: [service, config]
      Dependencies:
        properties:
          DependencyType:
            enum: [module, connector, feature]
      Capabilities:
        type: array
        items:
          - $ref: "#/definitions/Capability"
      