# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
  {{ range $key, $value := .Values.metadata.labels }}
    {{ $key }}: {{ $value }}
  {{ end }}        
data:
  file: "Hello {{ .Values.hello }}"