{{- if .Values.clusterScoped }}
{{- if include "fybrik.npServiceProcessing" . }}
{{- if .Values.worker.npIsolation.clusterLevelServicesAccess}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fybrik.fullname" . }}-np-services-cr
rules:
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - get
    - list
    - watch
{{- end }}
{{- end }}
{{- end }}