{{- if and .Values.worker.enabled .Values.worker.npIsolation.enabled }}
{{- if and .Values.clusterScoped .Values.worker.npIsolation.clusterLevelServicesAccess}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fybrik.fullname" . }}-np-services-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fybrik.fullname" . }}-np-services-cr
subjects:
  - kind: ServiceAccount
    name: {{ .Values.manager.serviceAccount.name | default "default" }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
