{{- if .Values.manager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fybrik.fullname" . }}-system-role
{{- if .Values.systemNamespace }}
  namespace: {{ .Values.systemNamespace }}
{{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - plotters
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - plotters/status
  - blueprints/status
  verbs:
  - get
  - patch
  - update
{{- end }}
