{{- if .Values.worker.enabled }}
{{- if .Values.worker.npIsolation.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fybrik.fullname" . }}-blueprints-default-deny-all
  namespace: {{ include "fybrik.getModulesNamespace" .}}
spec:
  podSelector: { }
  policyTypes:
    - Ingress
{{- end }}
{{- end }}
