{{- if and .Values.worker.enabled .Values.worker.npIsolation.enabled }}
{{- if and .Values.clusterScoped .Values.worker.npIsolation.clusterLevelServicesAccess}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fybrik.fullname" . }}-np-services-cr
rules:
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - get
    - list
    - watch
{{- end }}
{{- end }}
