{{- if .Values.worker.enabled }}
{{- if .Values.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
<<<<<<< HEAD:charts/fybrik/templates/motion-role.yaml
  name: {{ template "m4d.fullname" . }}-motion-role
=======
  name: {{ template "fybrik.fullname" . }}-motion-cr
>>>>>>> upstream/master:charts/fybrik/templates/motion-cr.yaml
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  - deployments/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
{{- end }}
{{- end }}

