apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: m4d
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: m4d
    app.kubernetes.io/version: latest
    helm.sh/chart: m4d-0.0.0
  name: m4d-leader-election-role
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
