apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opa-policy-editor
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - patch
