apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: connector-ingress-security
spec:
  podSelector:
    matchLabels:
      m4d.ibm.com/componentType: connector
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          m4d.com/namespaceType: control-plane
