# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["https://kind-registry:5000"]
  [plugin."io.containerd.grpc.v1.cri".registry.configs."kind-registry".tls]
    insecure_skip_verify = true
  [plugin."io.containerd.grpc.v1.cri".registry.configs."kind-registry:5000".tls]
    insecure_skip_verify = true