---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - m4dmodules.app.m4d.ibm.com.yaml
  - batchtransfers.motion.m4d.ibm.com.yaml
  - assets.katalog.m4d.ibm.com.yaml
  - blueprints.app.m4d.ibm.com.yaml
  - m4dstorageaccounts.app.m4d.ibm.com.yaml
  - plotters.app.m4d.ibm.com.yaml
  - m4dapplications.app.m4d.ibm.com.yaml
  - streamtransfers.motion.m4d.ibm.com.yaml
