definitions:
  InfrastructureElement:
    oneOf:
      - properties:
          attribute:
            enum: [storage-cost]
          units:
            enum: [US Dollar]
        required: [attribute, units]
      - properties:
          attribute:
            enum: [bandwidth]
          units:
            enum: [TB/s, GB/s, MB/s]
        required: [attribute, units]
      - properties:
          attribute:
            enum: [size]
          units:
            enum: [TB, GB, MB, KB]
        required: [attribute, units]
