definitions:
  InfrastructureMetrics:
    oneOf:
      - properties:
          name:
            enum: [cost, storage-cost]
          units:
            enum: [US Dollar per TB per month]
        required: [name, units]
      - properties:
          name:
            enum: [bandwidth]
          units:
            enum: [Mbps, Gbps, Tbps, Kbps, MBps, GBps, TBps, KBps]
        required: [name, units]
      - properties:
          name:
            enum: [size]
          units:
            enum: [TB, GB, MB, KB]
        required: [name, units]
      - properties:
          name:
            enum: [distance]
          units:
            enum: [m, km]
        required: [name, units]        
