{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.openPolicyAgentConnector.enabled $autoFlag) }}
{{- if .Values.openPolicyAgentConnector.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: openapi-opa-conn
  labels:
    app.kubernetes.io/component: openapi-opa-conn
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openapi-opa-conn
  minReplicas: {{ .Values.openPolicyAgentConnector.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.openPolicyAgentConnector.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.openPolicyAgentConnector.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.openPolicyAgentConnector.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.openPolicyAgentConnector.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.openPolicyAgentConnector.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
