# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: secret-provider
  labels:
    app: secret-provider
spec:
  ports:
  - port: 5555
    name: http
  selector:
    app: secret-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-provider
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: secret-provider
    spec:
      serviceAccountName: secret-provider
      containers:
      - name: server
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        image: secret-provider
        command: ["python3", "server.py"]
        args:
        - --config
        - /run/secret-provider/config.conf
        - --logging
        - info
        volumeMounts:
        - name: secret-provider-config
          mountPath: /run/secret-provider
          readOnly: true
      volumes:
      - name: secret-provider-config
        configMap:
          name: secret-provider-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-provider-configmap
  #namespace: m4d-system
data:
  config.conf: |
    vault_address = "http://vault.m4d-system.svc.cluster.local:8200"
    vault_path = "/v1/auth/kubernetes/login"
    iam_endpoint = "https://iam.cloud.ibm.com/identity/token"
    jwt_location = "/var/run/secrets/kubernetes.io/serviceaccount/token"
