openapi: 3.0.1
info:
  version: 1.0.0
  title: Policy Manager Service
  license:
    name: Apache 2.0
servers:
  - url: https://localhost:8080
paths:
  /getPoliciesDecisions:
    post:
      summary: getPoliciesDecisions.
      parameters:
        - name: input
          description: Policy Manager Request Object
          required: true
          in: query
          content:
            application/json:
              schema:
                type: object
                $ref: "../../charts/fybrik/files/taxonomy/policy_manager_request.json"
        - name: creds
          description: credentials to wkc connector
          required: true
          in: query
        - in: header
          name: X-Request-Cred
          schema:
            type: string
          required: true
      requestBody:
        description: Policy Manager Request Object.
        required: true
        content:
          application/json: 
            schema:
              type: object
              $ref: "./objects/policy_manager_request.json"   
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: "../../charts/fybrik/files/taxonomy/policy_manager_response.json"
        '400':
          description: Invalid status value