openapi: 3.0.1
info:
  version: 1.0.0
  title: Policy Manager Specification
  license:
    name: IBM
paths: {}
components:
  schemas:
    PolicyManagerRequest:
      $ref: "./objects/policy_manager_request.json"
    PolicyManagerResponse:
      $ref: "./objects/policy_manager_response.json"