openapi: 3.0.1
info:
  version: 1.0.0
  title: Policy Manager Taxonomy
  license:
    name: IBM
servers:
  - url: https://localhost:8080
paths:
  /getPoliciesDecisions:
    get:
      summary: getPoliciesDecisions
      description: Rest API for returning policy decisions
      operationId: getPoliciesDecisions
      parameters:
        - name: input
          description: Policy Manager Request Object 
          required: true
          in: query
          content:
            application/json:
              schema:
                type: object
                $ref: "./objects/policy_manager_request.yaml"
        - name: creds
          description: credentials to wkc connector
          required: true
          in: query
          schema:
            type: string                
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: "./objects/policy_manager_response.yaml"
        '400':
          description: Invalid status value