apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: data-csv
  namespace: default
spec:
  vaultPluginPath: vaultPluginPath
  details:
    dataFormat: csv
    connection:
      name: s3
      s3:
        endpoint: "http://minio:9000"
        bucket: demo
        objectKey: data.csv
  resource:
    name: demoAsset
    owner: Alice
    geography: us-south
    tags:
      tag: PII
    columns:
      - name: c1
        tags:
          tag: PII