apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-provider
  name: secret-provider
  namespace: m4d-system
spec:
  ports:
  - name: http
    port: 5555
  selector:
    app: secret-provider
