apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fybrik-admin-cr
rules:
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikapplications/status
  verbs:
  - get
  - patch
  - update
