# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: m4d-system

bases:
- ../default

resources:
- deployment_configmap.yaml
- datacatalog.yaml
- policycompiler.yaml

patchesStrategicMerge:
- manager_patch.yaml