# Source: fybrik/templates/fybrik-blueprints-ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fybrik-blueprints
---
# Source: fybrik/templates/fybrik-admin-cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fybrik-admin-cr
rules:
  - apiGroups:
      - app.fybrik.io
    resources:
      - fybrikapplications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - app.fybrik.io
    resources:
      - fybrikapplications/status
    verbs:
      - get
      - patch
      - update
---
# Source: fybrik/templates/fybrik-user-cr.yaml
# ClusterRole fybrik-user allows managing fybrikapplications
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fybrik-user
rules:
  - apiGroups: ["app.fybrik.io"]
    resources: ["fybrikapplications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["app.fybrik.io"]
    resources: ["fybrikapplications/status"]
    verbs: ["get", "update", "patch"]
---
# Source: fybrik/templates/katalog-connector/katalog-rbac.yaml
# ClusterRole katalog-editor allows managing assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-editor
rules:
  - apiGroups: ["katalog.fybrik.io"]
    resources: ["assets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
# Source: fybrik/templates/katalog-connector/katalog-rbac.yaml
# ClusterRole katalog-viewer allows viewing assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-viewer
rules:
  - apiGroups: ["katalog.fybrik.io"]
    resources: ["assets"]
    verbs: ["get", "list", "watch"]
---
# Source: fybrik/templates/manager-auth-proxy-cr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fybrik-proxy-cr
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
---
# Source: fybrik/templates/fybrik-admin-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fybrik-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fybrik-admin-cr
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: fybrik-system
---
# Source: fybrik/templates/katalog-connector/katalog-connector-rbac.yaml
# Grant katalog-connector the katalog-editor Role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-connector-editor
roleRef:
  kind: ClusterRole
  name: katalog-editor
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: katalog-connector
    namespace: fybrik-system
---
# Source: fybrik/templates/manager-auth-proxy-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fybrik-proxy-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fybrik-proxy-cr
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: fybrik-system
---
# Source: fybrik/templates/webhook-configs.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: 'fybrik-system-mutating-webhook'
  annotations:
    cert-manager.io/inject-ca-from: 'fybrik-system/serving-cert'
    certmanager.k8s.io/inject-ca-from: 'fybrik-system/serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: 'fybrik-system'
        path: /mutate-motion-fybrik-io-v1alpha1-batchtransfer
    failurePolicy: Fail
    name: mbatchtransfer.kb.io
    rules:
      - apiGroups:
          - motion.fybrik.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - batchtransfers
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: 'fybrik-system'
        path: /mutate-motion-fybrik-io-v1alpha1-streamtransfer
    failurePolicy: Fail
    name: mstreamtransfer.kb.io
    rules:
      - apiGroups:
          - motion.fybrik.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - streamtransfers
    sideEffects: None
---
# Source: fybrik/templates/webhook-configs.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: 'fybrik-system-validating-webhook'
  annotations:
    cert-manager.io/inject-ca-from: 'fybrik-system/serving-cert'
    certmanager.k8s.io/inject-ca-from: 'fybrik-system/serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: 'fybrik-system'
        path: /validate-app-fybrik-io-v1alpha1-fybrikapplication
    failurePolicy: Fail
    name: vfybrikapplication.kb.io
    rules:
      - apiGroups:
          - app.fybrik.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fybrikapplications
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: 'fybrik-system'
        path: /validate-motion-fybrik-io-v1alpha1-batchtransfer
    failurePolicy: Fail
    name: vbatchtransfer.kb.io
    rules:
      - apiGroups:
          - motion.fybrik.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - batchtransfers
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: 'fybrik-system'
        path: /validate-motion-fybrik-io-v1alpha1-streamtransfer
    failurePolicy: Fail
    name: vstreamtransfer.kb.io
    rules:
      - apiGroups:
          - motion.fybrik.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - streamtransfers
    sideEffects: None
