{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "openmetadata") }}
{{- if include "fybrik.isEnabled" (tuple .Values.openmetadataConnector.enabled $autoFlag) }}
# openmetadata-editor allows managing assets
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.clusterScoped }}
kind: ClusterRole
metadata:
  name: {{ template "fybrik.fullname" . }}-openmetadata-editor-cr
{{- else }}
kind: Role
metadata:
  name: {{ template "fybrik.fullname" . }}-openmetadata-editor-role
  namespace: {{ .Values.applicationNamespace | default .Release.Namespace  }}
{{- end }}
rules:
- apiGroups: ["openmetadata.fybrik.io"]
  resources: ["assets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
{{- end }}
