# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: 'cert-manager-{{name}}' # 'name' field of the Secret
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.6.2
        helm:
          parameters:
          - name: installCRDs
            value: 'true'

      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: cert-manager

