# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://github.com/fybrik/charts'
    path: charts/vault
    targetRevision: HEAD
    helm:
      valueFiles:
        - env/dev/vault-single-cluster-values.yaml
      parameters:
        # authDelegator enables a cluster role binding to be attached to the service account.
        # The cluster role binding is already deployed in the smaug cluster and thus authDelegator can be disabled.
        - name: vault.injector.enabled
          value: 'false'
        - name: vault.server.dev.enabled
          value: 'true'
  destination:
    namespace: fybrik-system
    name: coordinator
