apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: fybrik-system/serving-cert
    certmanager.k8s.io/inject-ca-from: fybrik-system/serving-cert
  creationTimestamp: null
  name: fybrik-system-mutating-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: fybrik-system
      path: /mutate-motion-fybrik-io-v1alpha1-batchtransfer
  failurePolicy: Fail
  name: mbatchtransfer.kb.io
  rules:
  - apiGroups:
    - motion.fybrik.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - batchtransfers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: fybrik-system
      path: /mutate-motion-fybrik-io-v1alpha1-streamtransfer
  failurePolicy: Fail
  name: mstreamtransfer.kb.io
  rules:
  - apiGroups:
    - motion.fybrik.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streamtransfers
  sideEffects: None
