name: Build

on:
  push:
    branches:
      - github_actions_tests
#  pull_request:
#    branches:
#      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_USERNAME: the-mesh-for-data
  ACTIVE_CI: travisci # This parameter defines which CI should push to the docker repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/go/pkg/mod
            ${{ github.workspace }}/hack/tools/bin
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-go-${{ hashFiles('**/go.sum') }}
    #          restore-keys: ${{ runner.os }}-m2
      - name: Install tools
        run: make install-tools
      - name: Verify
        run: make verify
      - name: Test
        run: make test