name: Website Preview
on:
  pull_request_target:
    branches:
      - master
    types: 
      - opened
      - synchronize
    paths:
      - site/**
      - pkg/connectors/protos/**
      - charts/m4d-crd/templates/**

jobs:
  website-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Material for MkDocs
        run: |
          pip install mkdocs-material
      - name: Build
        run: mkdocs build -f site/mkdocs.yml -d public
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './site/public'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
