definitions:
  Action:
    oneOf:
      - $ref: "#/definitions/RedactAction"
      - $ref: "#/definitions/RemoveAction"
      - $ref: "#/definitions/DenyAccess"
  RedactAction:
    type: object
    properties:
      columns:
        items:
          type: string
        type: array
    required:
      - columns
  RemoveAction:
    type: object
    properties:
      columns:
        items:
          type: string
        type: array
    required:
      - columns
  DenyAccess:
    type: object