# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.m4d.ibm.com/v1alpha1
kind: BatchTransfer
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
  {{ range $key, $value := .Values.metadata.labels }}
    {{ $key }}: {{ $value }}
  {{ end }}        
spec:
  source:
    s3:
      endpoint: "{{ .Values.source.connection.s3.endpoint }}"
      bucket: "{{ .Values.source.connection.s3.bucket }}"
      objectKey: "{{ .Values.source.connection.s3.object_key }}"
      dataFormat: "{{ .Values.source.format }}"
      vaultPath: "{{ .Values.source.credentialLocation }}"
  destination:
    s3:
      endpoint: "{{ .Values.destination.connection.s3.endpoint }}"
      bucket: "{{ .Values.destination.connection.s3.bucket }}"
      objectKey: "{{ .Values.destination.connection.s3.object_key }}"
      dataFormat: "{{ .Values.destination.format }}"
      vaultPath: "{{ .Values.destination.credentialLocation }}"
  transformation:
  {{- range $transformations := .Values.transformations }}
  - name: "{{ $transformations.name }}"
    action: "{{ $transformations.action }}"
    columns: {{ $transformations.columns }}
  {{- end }}
  secretProviderURL: "http://secret-provider.secret-provider.svc.cluster.local:5555/get-secret"
  secretProviderRole: demo
  image: ghcr.io/the-mesh-for-data/mover:latest
  imagePullPolicy: "IfNotPresent"
  noFinalizer: true
